nf_core_version: 3.3.2
repository_type: pipeline
lint:
  nf_test_content: False # skip nf-core test content
  actions_nf_test: False # skip GitHub Action test check
  actions_awsfulltest: False # skip AWS workflow test check

  files_unchanged:
    - docs/README.md
    - .gitignore
    - .prettierignore

  nextflow_config:
    - manifest.name
    - manifest.homePage
    - manifest.version
